### ISSUE TITLE
Replay protection

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#102]
We should ensure that there is adequate anti-replay protection for both Handshake and Application messages.  (In particular, we should define what anti-replay issues are a concern.)  Could be related to #101 if we want to solve it at that framing layer.

**Comment by alexsherkin** [comment]
It looks like application key schedule on its own may not be enough to prevent replay attacks if out-of-order messages are supported (and it seems like they are supported according to section 9.2.1).

Lets say we are at epoch x, and the receiver derives application_secret_[sender]_[0] for epoch x. Then, the receiver receives message1 (generation = 1) first before message0. In order to decrypt message1, the receiver needs to advance the application secret forward once to application_secret_[sender]_[1] to get message1 nonce and AEAD secret. The receiver then happily processes message 1. However, the receiver cannot forget application_secret_[sender]_[0] at this time; otherwise it will never be able to decrypt message0 so it has to keep application_secret_[sender]_[0] around.

If the receiver receives message1 again, it can compute application_secret_[sender]_[1] from application_secret_[sender]_[0] and process the message. Hence, it seems that key schedule on its own will not prevent replay attacks. The receiver needs to remember that it has already processed message1.

The same problem may apply to receiving a message from epoch N+1 while not all messages from epoch N have been received (if such case is possible).

Replay attack counter-measures may be implemented as part of key schedule logic or separately, but it looks like implementors need to pay attention to this.

**Comment by beurdouche** [comment]
Obviously, if you keep a previous application secret, you are breaking FS. This is forbidden by the protocol. The protocol mandates: "Receivers MUST delete an Application Secret once it has been used to derive the corresponding AEAD key and nonce as well as the next Application Secret. Receivers MAY keep the AEAD key and nonce around for some reasonable period."

**Comment by beurdouche** [comment]
Cf. "Updating the Application Secret"

**Comment by alexsherkin** [comment]
Does it mean that receiving out-of-order messages is not possible? If I abandon application_secret_[sender][0] and advance to application_secret_[sender][2] after receiving message 1 before message 0, I will never be able to process message 0. Is this intended behavior or am I missing something?

**Comment by beurdouche** [comment]
No, you can do out of order, but what you keep are the AEAD keys/nonces and not the Application Secrets. 

The idea is the following:
1 - Compute Application Secret[sender][0]
2 - Derive AEAD Key[Sender][0] and AEAD Nonce[Sender][0] from Application Secret[sender][0]
3 - Overwrite Application Secret[sender][0] with Application Secret[sender][1]
Basically, you should see these 3 steps as a single operation
Now, if you iterate over that you can get more AEAD Keys and nonces [0 ... N] to receive out of order.
Because of step 3 you have local Forward Secrecy. Note that you never store more than a single (the latest) Application Secret and that you have the keys [0...N] to decrypt out of order.

**Comment by alexsherkin** [comment]
Makes sense. Thanks for explaining. I suspect receiving out of order messages from a different epoch works in a similar way. If I am at epoch 0, and I receive a message from epoch 2, I derive and keep application_secret for epoch 1 and roll the init_secret forward.

From the implementation perspective, how do I know when I can safely discard an application secret for a particular epoch? Or how do I know that no more messages are coming for a particular sender/epoch?

Do you think there is value in adding a paragraph clarifying how the key schedule ensures replay attack protection to the spec? I know these are probably all implementation questions, but I suspect these may be the questions the implementors may be asking.

**Comment by beurdouche** [comment]
@alexsherkin 

I have some text stashed for when to discard the previous application secrets after there is a new epoch, so I will handle that. The idea is that you "publish" the number of application messages you sent in the previous epoch, but that is to be discussed...

Regarding replay, if you asked, it means clarification might be helpful here, do you want to submit a PR and assign me for review ? Otherwise just tell me and I'll handle it... : )

**Comment by alexsherkin** [comment]
@beurdouche I think you should review the below and update the spec as you see fit : )

-- I would update section 9.2.1 with something like:

If receiver's application secret is at generation N, and the receiver receives an out of order message with generation N+x (where x>0), the receiver MUST advance the application secret forward to application secret N+x+1 after processing the out of order message. For every message with generation between N and N+x-1 (messages that have not been received), the receiver SHOULD derive AEAD nonce and AEAD key and store them in order to be able to decrypt these messages later. Application secret MUST NOT be kept at generation N in order allow for decryption of out-of-order messages. Instead, stored AEAD key and nonce will allow for decryption of out-of-order messages when received later.


-- We may also introduce a short new section "Message Replay Protection" with something like:

Application key schedule provides replay attack counter-measures. If a message is replayed, the receiver should not have the right AEAD key nor have the application secret that could be used for deriving the right AEAD key for the replayed message. Hence, replayed message will be rejected by the receiver.

**Comment by bifurcation** [comment]
I think this is adequately addressed by #146 and #155
