### ISSUE TITLE
Re-randomize TreeKEM keys

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#228]
At the 2019-10 interim, @psyoptix described some work to re-randomize the tree as updates happen:

* Distribute `(Enc(r), g^r)` in Update/Commit message
* Transform the recipient public key as `x -> x+r, g^x -> g^{x+r}`

Benefits are roughly some better FS properties, to be described in a forthcoming ePrint.

Costs:
* Additional public key in `DirectPath`
* Restriction to curves with homomorphic multiplication (in particular, X25519->Ristretto)
* Possibly harder modeling

**Comment by psyoptix** [comment]
Improvement to construction which allows using X25510/X448
- Basic Idea: Use multiplicative "updateable PKE" instead of additive.

When sending HPKE ciphertext for some message m to (pk, sk) in Update/Commit do:
1) Sample re-randomizer r'. Compute re-randomizer scalar r = HKDF(r, pk, context...).
2) Transform receiver's pk from g^x -> (g^x)^r = g^xr'=: pk'. Send  c <-- Enc(pk, r'|| m). Send (pk', c)
3) Receiver use sk to decrypt c. gets m and r'. compute r. Update sk x to sk' := xr.

See "UPKE for X25519/X448" and draft-barnes-cfrg-mult-for-7748-00 RFC draft for how to implement "*" operation for updating sk --> sk' when using X25519/X448 curves.

**Comment by bifurcation** [comment]
This was discussed at the January 2020 interim, with the conclusion that while this an interesting idea, it would be better handled as an extension.
