### ISSUE TITLE
Relax default policy of adding from left to right

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-protocol#266]
The current default strategy (add from left to right) doesn't allow for flexibility in forming optimized subgroups.
It also isn't super good for privacy: a newcomer should not be able to infer who is the creator of the group at epoch 0 from its position in the tree except when she is in the initial participants...

**Comment by bifurcation** [comment]
Is it only the creator you're worried about?  If so, then we should be able to address that just by having the creator put themselves elsewhere in the tree.

I'm also not convinced that this is an aspect of privacy that I really care about enough to design much mechanism around it.  It only applies at group creation time anyway, since after that, a new joiner doesn't know if member 0 is the creator or someone who was added after.
