### ISSUE TITLE
Add extensions to the Commit message

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#366]
[This issue is part of a feature breakdown based on #336]

Applications might want to signal to group members  processing a commit that they should take certain actions in addition to ratcheting the group forward.  The most obvious example is folding in a PSK for the epoch, but you can also imagine addressing things like transcript consistency or updatable PKE through this channel.

This should be straightforward syntactically, but will also require updating the extensibility section to make clear that Commit extensions can also in principle affect the GroupContext extensions.  In other words:

* Each group member associates a list of extensions with the group, which are confirmed via the GroupContext
* New joiners get configured with these via extensions in the GroupInfo
* Existing members can find out about changes to the group's extensions via extensions in the Commit

**Comment by kkohbrok** [comment]
I think making commit messages extensible is a great idea. However, I'd like to understand better what we want to use the extensions first. 

> Applications might want to signal to group members processing a commit that they should take certain actions in addition to ratcheting the group forward.

I thought that was what Proposals are for. I think for mechanisms that are part of the base protocol spec, there is no reason not to extend the list of proposals.

Regarding the nature of extensions: Do I understand correctly, that an extension is a property of the group first and foremost? And extensions in the commit are meant to alert other group members to changes in those properties? Or are extensions in the commit messages a mechanism to allow for the inclusion of additional data in the commits? Or both? I feel like the meaning of the word "extension" is a little stretched here.

Since we're discussing this also in the context of PSK injections: Do you think PSK injections should be something that can be switched on and off for any given group? If so, why? I would consider it part of the base protocol and do not see what benefits we get from disallowing it in a group.

**Comment by bifurcation** [comment]
It's a fair point, that we have basically two extension points here -- proposal types and extensions.  I think the theory I had in mind was something like:

1. Proposals describe modifications you make to the tree before you use it for TreeKEM (to get the path) (if you do)
2. The DirectPath describes the outcome of TreeKEM.Encap
3. Extensions tell you anything else you need to do

If that philosophy makes sense, I can update the PR to make that clearer.

Note that proposal extensibility is currently broken because we don't actually have a way for the Commit to include any Proposals with new proposal types.  I've filed #383 for that.

**Comment by bifurcation** [comment]
On the nature of extensions: My thinking here is that an "extension" is purely syntactic; its semantics are defined entirely by its ExtensionType.  One thing that extensions do (in the context of GroupContext) is express what attributes/parameters the group has agreed to.  But they can also do other things.

**Comment by bifurcation** [comment]
On PSK injections: My thinking here is that PSKs are a per-epoch decision, in that you can inject a different set of PSKs at each epoch.  Since the Commit is the thing that starts a new epoch, it signals what PSKs to use for that epoch.  A few illustrative cases:

- A "meeting password" might get injected on every commit
- ... or you might only inject it in commits where you have an Add, to verify that the new guy has it
- In a scenario where you have some OOB PSK distribution (say to add more PQ safety), you would inject a PSK every epoch, but a different one in each epoch
- When re-starting a group or branching a subgroup, you would incorporate the resumption secret from the previous group, but then might not need a PSK ever again.

**Comment by kkohbrok** [comment]
I see, thanks for the clarification. My understanding of extensions was that their advantage is that they're dynamic and can be defined and used after MLS is defined, i.e. to keep the standard extensible. I know that in the TLS context, extensions are used for all sorts of basic protocol behaviour, but my understanding was that was more something that has evolved over time rather than it being "by-design".

Is there any reason for Proposals to be limited to TreeKEM operations (other than that being their historic purpose)? Because otherwise it seems a little odd to me not to use them for core MLS operations such as PSK injection.

**Comment by kkohbrok** [comment]
Otherwise, I agree with your take on PSK injections. They should definitely be part of the commit and it should be possible to inject them ad-hoc. Although for the re-starting or branching use-case, I think they should be part of the Welcome message, but I think we're having that discussion on the mailing list already.

**Comment by bifurcation** [comment]
This was discussed at the interim on 2020-08-25.  The feeling of the group was that Proposals should be a sufficient extension mechanism for Commits, so we don't need this if we fix #383.  And since #389 is about to do that, closing this issue.
