### ISSUE TITLE
Address DoS by malicious insiders

### ISSUE THREAD

**Issue by tomtau** [mlswg/mls-protocol#373]
https://github.com/mlswg/mls-protocol/issues/21

In the current protocol draft:
```
<!-- OPEN ISSUE: It is not possible for the recipient of a handshake
message to verify that ratchet tree information in the message is
accurate, because each node can only compute the secret and private
key for nodes in its direct path.  This creates the possibility
that a malicious participant could cause a denial of service by sending a
handshake message with invalid values for public keys in the ratchet
tree. -->
```

Unless I overlooked it, the current draft seems to be also missing a "simple" DoS case where a handshake message could omit / malform some `DirectPathNode` (e.g. by having an empty ciphertext or invalid kem_output) -- this should be easily detectable (either by members themselves or if handshake messages are transmitted as MLSPlaintext, the delivery service could reject that).

For that originally discussed case, I guess the sketched out solution with a "Nack" message containing a DLEQ proof could work. Besides the drawbacks described there, one will also need to extend HPKE definitions to allow for this "directly decrypt from the revealed shared secret" use case.

**Comment by bifurcation** [comment]
You're correct that there is a simpler DoS case where the sender could simply send a malformed `DirectPathNode`.  It shares with the DoS described that it is only detectable by affected nodes.   And I think that those two together cover the DoS possibilities, since it covers the two things that can be chosen in Commit.

As far as Nack/DLEQ -- I'm not sure what you have in mind there.  It seems like you would want zero-knowledge proofs for two relationships between HPKE ciphertexts: (1) that two ciphertexts are encryptions of the same value under two different public keys, and (2) that a parent ciphertext is an encryption of the parent node secret, and the child ciphertext is an encryption of the child node secret.  It's not clear that there are solutions for either of these.

What we can do though, is make sure that the Security Considerations cover these risks.  I would propose focusing on documenting the risk rather than fixing it.

**Comment by tomtau** [comment]
> It shares with the DoS described that it is only detectable by affected nodes.

For that simpler case, it can be detected by other nodes by doing extra checks (e.g. checking all `DirectPathNode` cipher text lengths or public key formats match what one would expect in a particular ciphersuite).

> As far as Nack/DLEQ -- I'm not sure what you have in mind there.

I was referring to the final comments here: https://github.com/mlswg/mls-protocol/issues/21#issuecomment-455392023
So, the goal won't be to prevent malicious insiders, but allow affected nodes to report that they couldn't process Commit by revealing the corresponding ephemeral key. With HPKE / current draft, it may be:
- for malformed path secrets, affected nodes reveal `dh` + `DLEQ(dh:kem_output :: node_public_key:G)`
- others check DLEQ; then using `dh` compute `zz` for `SetupBaseR` and can go ahead to check the path secrets (either the ciphertext is malformed or the public keys derived from secrets don't match the received public keys in Commit)

**Comment by bifurcation** [comment]
Discussed on virtual interim 2020-10-20: Closing pending a more detailed proposal.
