### ISSUE TITLE
Mandatory Extensions vs. Fields

### ISSUE THREAD

**Issue by kkohbrok** [mlswg/mls-protocol#405]
Why are extensions that MUST be present in an instance of a struct (e.g. `capabilities` and `lifetime` in a `KeyPackage`) not just fields in that struct?

Shouldn't `extensions` be used for custom extensions or maybe optional parts of the struct? (Although those should probably be `optional` fields, I would think.)

**Comment by bifurcation** [comment]
I don't have a strong feeling on this.  The best argument that comes to my mind is that it makes changes in the future a bit easier, since adding/removing extensions is a bit easier than changing the base struct.  The [TLS 1.3 ClientHello](https://tools.ietf.org/html/rfc8446#section-4.1.2), for example, has fields like `legacy_version` that have been deprecated because they found a better way to do things like version negotiation.  

@Bren2010 @raphaelrobert maybe you guys have opinions?

**Comment by Bren2010** [comment]
I believe this has been brought up before, but you said you wanted them to be extensions because it forces people to actually implement the extensibility logic. I would like them to be fields but that was a good enough argument that I left it alone

**Comment by kkohbrok** [comment]
Thanks for elaborating on this. I also prefer fields, but given those arguments, I'm happy to have them as extensions as well.
