### ISSUE TITLE
Mandatory extension types?

### ISSUE THREAD

**Issue by rohan-wire** [mlswg/mls-protocol#485]
Many protocols which have an extensibility mechanism have a way to indicate that understanding an extension is mandatory for certain behaviors. For MLS, this would mean having a way to require a member understand an MLS extension before it can join a group. The three extension types defined currently are: 
 MLS ciphersuites, 
 MLS extension types, and 
 MLS credential types. 

One logical way to add mandatory extensions would be to pick one of these types (the MLS extensions type) and use the high order bit or a specific range to indicate that a member must understand and implement the extension to join a group which uses that extension. The IANA values could be changed as follows:

Values from 0x8000-0xffff indicate understanding the extension is required
0x7f00 - 0x7fff  Reserved for Private Use (not required)
0xff00 - 0xfff   Reserved for Private Use (required)

If a required ciphersuite or credential becomes necessary, a new extension type could be created to add an extension in the KeyPackage or GroupInfo which would be required and would indicate support for the mandatory ciphersuites or credentials.

In order to prevent some other entity from adding an MLS client that does not support a mandatory extension, we already have the KeyPackage Client Capabilities, which lists which extensions are supported by the client.

**Comment by bifurcation** [comment]
Note that though this might seem "now or never", I don't think it really
is.  Consider TLS by way of analogy -- it has no mechanism for specifying
that extensions are required.  But if a server gets a ClientHello that is
missing some extension that it requires, it can just abort the handshake.
Likewise in MLS, the member adding a new joiner to the group can examine
that joiner's KeyPackage to see if they support the extensions needed for
the group.

So I think you could implement this as a non-mandatory GroupContext
extension, which would state the extensions required by the group so that
all members apply the same requirements for new joiners.

--Richard

**Comment by rohan-wire** [comment]
While you can implement this "out-of-band", that makes it implicit rather than explicit behavior.

**Comment by seanturner** [comment]
Discussed at 20211004 interim, liked this functionality. But, instead of IANA registry use field (or extension) in group context to indicate which extensions are required.

@rohan-wire to generate PR.

**Comment by rohan-wire** [comment]
Discussed with @bifurcation and incorporated this functionality into PR #489
