### ISSUE TITLE
Discard pending Update proposals for the sender if a `path` is included

### ISSUE THREAD

**Issue by kkohbrok** [mlswg/mls-protocol#516]
Any Update proposal for the sender is redundant if the Commit includes a `path`.

**Comment by bifurcation** [comment]
This is true, but they're also harmless, since the information in the `path` will overwrite all of their effects.

Note that:
* A requirement to this effect would only be binding on a committer.  The receiver of a Commit MUST process all of the referenced proposals, as prescribed in the Commit.
* A `path` is required if a Commit covers Updates or Removes; if a Commit covers a self-Update, then it must have a `path`.   So there's no reasn to condition on "if a `path` is included".

This seems fine for some advisory text, but not an absolute prohibition.

**Comment by kkohbrok** [comment]
The way I read Section 11.2 is that the receiver should verify that the committer has followed the rules, e.g. that the commit contains all valid proposals, etc., even if that is not explicit in the list of things the receiver of a commit should do. So any requirement on the committer would also affect the receiver. So if we mandate that a committer can't include self-updates if the path is populated, then it would be implicit that the receiver checks that the committer actually followed the rules when processing a commit.

I'm not sure I understand your second point. My reasoning would be that if a committer wants to do an update, they would just include a path rather than an update proposal, which is redundant anyway.

**Comment by kkohbrok** [comment]
I'm ok with the solution in #517, although I would have preferred ruling out self-update proposals in commits entirely. That being said, I have to say that I find it a bit irritating that the issue was closed. I had the impression that there was still a conversation going on.

**Comment by bifurcation** [comment]
Sorry @kkohbrok, I missed that there was still conversation going on here before merging #517.

On the latter point: All I'm saying is that there is no case where there is both (a) a self-update and (b) no `path`.  So you're always in the bad scenario :)

In our Wire chat, you made a good point that repeated proposals for the same leaf are invalid, and self-Updates are effectively repeats of the `path`.  Reopening, will  file a fresh PR to adjust the text.
