### ISSUE TITLE
Clarity around extensions and `RequiredCapabilities`

### ISSUE THREAD

**Issue by tomleavy** [mlswg/mls-protocol#537]
The description of `RequiredCapabilities` is clear that proposals defined in the RFC are not to be included because they are considered standard, however there is no such clarification around extensions. 

In general, extension requirements are not all that clear because in several places (such as Lifetime) it is mentioned that an extension must be included, however they are all listed as recommended rather than required in the table. It also raises a question in that if an extension is required to be implemented as part of the specification, and required in every KeyPackage, should it just be a field rather than an extension?

**Comment by kkohbrok** [comment]
> The description of `RequiredCapabilities` is clear that proposals defined in the RFC are not to be included because they are considered standard, however there is no such clarification around extensions.

Even that is not quite clear to me. At least to me it doesn't follow from Section 10.1.

> In general, extension requirements are not all that clear because in several places (such as Lifetime) it is mentioned that an extension must be included, however they are all listed as recommended rather than required in the table. It also raises a question in that if an extension is required to be implemented as part of the specification, and required in every KeyPackage, should it just be a field rather than an extension?

The last one at least, I can shed some light on, as we had this discussion before and I was arguing the same thing. From what I remember, the argument was the keeping it an extension rather than a field would force implementers to implement the Extension mechanism. I don't have a super strong opinion here, but I seem to remember that that's what it boiled down to.

I generally agree, though, that some things around RequiredCapabilities (RC) and Capabilities in general is unclear. I discussed this with @raphaelrobert and here are some examples/questions that came up:

* If a group doesn't have an RC extension, can we assume that all extensions/proposals in the spec are supported by everyone, or do we have to check all KeyPackages?
* Do we want all extensions/proposals in the spec to be MTI and thus implicitly supported by everyone? It might be useful to distinguish between basic (MTI) ones like Add, Remove, etc. and consider some optional such as ExternalInit or AppAck.
* Relatedly, should the `Capabilities` extension in the KeyPackage list all the Spec proposals/extensions, too? Are they invalid if they do or if they don't? 
* We might want to discuss the difference between RC and a potential group policy. The way I understand it, RC is not meant to be an allow list or a block list, but instead should specify a minimum requirement for all clients in the group. A question here would be: If it's not in the RC, but everyone's capabilities support it, can I use/send it?

**Comment by bifurcation** [comment]
Reacting to Konrad's points here:

* It seems like to to be sure, you always need to check.  RC just helps ensure that the check will produce the right answer.
* I would propose the answer to this be "Yes, the proposals/extensions in the spec are MTI"
* If the answer to the prior question is as I propose, then you don't need to list spec proposals/extensions in Capabilities
* The difference between RC and checking everyone supports it is whether we expect it to be supported in the future.  For Proposals, that might not matter; for GroupContext extensions, it matters more.

It also seems like there's a fair argument that RequiredCapabilities should just be removed from the spec and replaced by some application-layer coordinated policy.  I would be OK with that.

To @tomleavy's point about mandatory extensions -- I would probably be OK with converting mandatory extensions to fields, especially with the better division of labor proposed in #539.

**Comment by tomleavy** [comment]
I kind of like the idea of RequiredCapabilities because it enforces the proper checks lower down. Application layer would need to proxy packets via a middleware type of layer which could potentially be messy.
