### ISSUE TITLE
Proposals by reference in external commit

### ISSUE THREAD

**Issue by kkohbrok** [mlswg/mls-protocol#540]
The spec currently doesn't distinguish much between an external and a member commit w.r.t. how proposals by reference are handled. In theory, the server could keep track of proposals and send the external committer all proposals that were sent up until the time they want to commit externally. However, there are a few difficulties in committing proposals by reference in an external commit.

* Membership tags: The external committer doesn't have the ability to verify membership tags on proposals. This is probably not a show-stopper, as proposals still need to be signed by a group member, but if nothing else, this should be noted in the spec.
* Leaf positioning: The spec was changed such that the committer is added into the tree without an Add proposal being present. If there are other Add (and Remove) proposals present, it is unclear in what order they should be processed. Should the committer be added when the path is processed? Or should it still be processed as if it were an Add?

There are probably other things that can go wrong when committing referenced proposals externally, but those are the first that come to mind.

The simplest solution would be to simply ignore proposals by reference, although this would break the current principle that a commit must always include all valid proposals that were sent during the epoch. The consequence would be that Parties that sent proposals will have to re-send them if the epoch is ended by an external commit. It should be noted, that a Preconfigured sender will have no way to detect if their proposal was committed or not.

**Comment by bifurcation** [comment]
I'm not sure your worries here are very real:

* Membership tags: I don't think the membership tag issue matters, because the existing members will reject the proposal (and thus the commit) if the membership tag is invalid; at worst the joiner gets themselves wedged into a group by themselves.  And as you say, they're signed, and they keys can be tied back to the tree hash in the GroupInfo.
* Leaf positioning: We need to clear this up regardless of proposals-by-reference.  It seems like basically having a synthetic Add at the beginning or end of the proposal list would work fine.
* Preconfigured proposer: This is a problem only when Commits are encrypted, so it's not a problem in the external commit case (since an external Commit cannot be encrypted).

Nonetheless, the point that an external joiner can't fully verify a Proposal seems to argue pretty strongly for forbidding proposals by reference.  I don't think this even violates the semantic of "include all valid proposals received in the epoch", since (1) that requirement is receiver oriented (it's not enough for the proposals to have been sent) and (2) the external joiner can't tell if the proposals or valid.

Overall, I would lean slightly toward removing proposals by reference.  And if we do that, it might even make sense to just define an ExternalCommit message that packages together the few things that are still allowed.

**Comment by kkohbrok** [comment]
I'm not sure I understand how the receiver-orientation of the "all valid proposals must be included" rule matters to its application to this case. If we remove the requirement for external commits to include proposals by reference and don't soften that rule to exclude external commits, receivers will consider all external commits invalid in the presence of valid pending proposals by reference.

In any case, I'm also in favor of keeping it simple and restrict the External Commit to a few, well defined components that do not include any proposals by reference.

**Comment by bifurcation** [comment]
Discussion on working call:

* "No proposals by reference" kind of follows from "all _valid_ proposals", since the joiner can't necessarily determine that proposals are valid
* Maybe allow attempts?  Might not get feedback to retry, though.  Whole point of external commit is to allow async.
* Agreement to prohibit proposals by reference in external Commit
