### ISSUE TITLE
Conflicting proposal / commit behavior

### ISSUE THREAD

**Issue by tomleavy** [mlswg/mls-protocol#542]
There are several rules in terms of selecting proposals and issuing commits against them. I have distilled the existing wording in the document into the following rules

1. If there are multiple updates for the same leaf, cherry pick one.
2. If there is a remove and an update/add for the same key package, always choose remove
3. If there are multiple group context extension updates, cherry pick one
4. The sender of a commit MUST use all valid proposals it has received 
5. In the event that a valid proposal is omitted from the next Commit, the sender of the proposal SHOULD retransmit it in the new epoch

It seems that rule 4 and rule 5 conflict with each other in that one is suggesting that all proposals must be consumed or there should be a hard error, and the other assumes it is possible for a commit to purposefully leave out a proposal and it can optionally be retransmitted.

I have been trying to write code that reasonably handles the cherry picking logic around multiple proposals referencing the same key package or multiple changes to group context while also enforcing the "must use all valid proposals received" rule, and it does introduce some complexity that maybe would be avoided by just eliminating that rule?

**Comment by kkohbrok** [comment]
Good point. One situation where rule 5 would make sense is if we prohibit proposals by reference in external commits to solve the problems outlined in #540. Rule 5 would otherwise make sense in situations, where there's no agreement on whether a proposal is valid. One case where this is necessarily the case is the following: A remove proposal was sent, but the client that is to be removed is the committer in this epoch. The client can't commit their own removal, but the proposal is still technically valid from the proposer's point of view. 

There might be other situations, for example, where the application imposes some sort of policy that different clients interpret differently. This should be the application's problem, though.

**Comment by tomleavy** [comment]
I think what I'm trying to boil this down to is, should my implementation throw an error if all proposals are not consumed by the process of applying the commit I just received, I'm still thinking enforcing that would be too difficult to apply everywhere

**Comment by tomleavy** [comment]
@bifurcation that makes sense to me, I'll put up a PR to change to SHOULD
