### ISSUE TITLE
Remove redundant nodes from the tree

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#559]
Right now, the UpdatePath generation and processing algorithms populate "redundant" parent nodes in the tree, in the sense that they have only one child node.  These redundant nodes are harmless except that they make tree truncation less effective.  We should update the UpdatePath algorithms so that they do not add redundant nodes to the tree.

**Comment by raphaelrobert** [comment]
I think the definition of redundant is slightly different than what you propose. Redundant nodes are nodes with a resolution of only one leaf node, where all parent nodes are filtered out of the resolution. I think in the very early days we called that a "shadow".

With the definition you propose, I think it would become impossible to do the first-ever full commit in an otherwise empty tree.

**Comment by bifurcation** [comment]
Fixed by #587
