### ISSUE TITLE
Remove or refine preconfigured senders

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#616]
As [Raphael pointed out on the mailing list](https://mailarchive.ietf.org/arch/msg/mls/VWzhGx2XwgBqHoHIE0fvuZS1sm4/), the current preconfigured sender mechanism isn't interoperably specified.  There is no confirmation that the members of a group agree on who the allowed preconfigured senders are, so different members might respond differently.  It seems like there are two options here:

1. Add the required details.  We would need a `preconfigured_senders` extension to confirm agreement to use the mechanism at all, and would probably need to have a list of senders there as well.

2. Remove the feature from the base protocol.  Since an extension is required in any case, there's no pressing need to have the feature in the base protocol.

Personally, I would lean toward (2).  Early deployment experience doesn't show a lot of need for this feature.  For example, in Webex, we just have the server forward a KeyPackage instead of synthesizing an Add proposal under a preconfigured signer; the TLS authentication is as good as a preconfigured signer signature.  As long as the SenderType enum is around, the extension should be a small follow-on spec if it is really needed.

**Comment by tomleavy** [comment]
@psyoptix and I would probably prefer the first option. I will write up a more detailed reason and post to the mailing list, but the TLDR is basically that in a really long session in async messaging, server driven proposals save you from some painful logic, and the extension would improve this to allow for interop / federation cases.

**Comment by psyoptix** [comment]
I am pretty clearly in favor of option 1. Pre-configured senders are playing a key role for us in implementing automation of backend-initiated changes to the group. Things like:
 - initiating the removal of Bob('s phone) because his account (or device) was deprovisioned.
 - announcing a change to the group's properties due to system wide policy changes.
Having an audit trail (i.e. the preconfigured sender's signature on the proposal) makes this a lot easier for the group to authenticate why this action is being committed to by group members. (Also, external commits are not a good alternative as they have the unwanted side-effect of the preconfigured sender learning the new epoch's key schedule.)

As for how to agree on preconfigured sender public keys, I think a minimal solution could be to have a list of preconfigured sender public keys as a group context extension. We already have a mechanism to change it during the life time of the group (via group_context_extensions proposal) so its a pretty small change to the the RFC.

**Comment by bifurcation** [comment]
That sounds fine to me. @tomleavy want to write up a PR?  It seems like something of the following form:

```
## Preconfigured Senders Extension

[[ Introductory prose ]]

~~~
struct {
    BasicCredential senders<V>; // `identity` fields must be distinct
} PreconfiguredSenders;
~~~
```

The idea being that BasicCredential already has the (id, public key) pair that you would need, so you would just need to say that when `sender.type = preconfigured`, `sender.sender_id` is the `identity` field from the corresponding BasicCredential.  (Also probably rename `sender_id` to `identity`.)

**Comment by bifurcation** [comment]
Or actually, you could do things even more simply by just having the extension be a list of `SignaturePublicKey`, and having `sender_id` be a `uint32` index into the array.

**Comment by tomleavy** [comment]
Ok no problem. I'll take a look today and propose something and we can iterate

**Comment by tomleavy** [comment]
What do you think about it just being credential instead of basic credential?

**Comment by kkohbrok** [comment]
I had the same thought. Since I kicked off the discussion, I felt the need to take a stab at closing it and I included the input from this threat and the list. See #617.

**Comment by tomleavy** [comment]
Thanks @kkohbrok , glad I put this off until now :-) I'll take a look at your PR
