### ISSUE TITLE
Secrets and Keys

### ISSUE THREAD

**Issue by br-hale** [mlswg/mls-protocol#630]
The spec currently uses a mix of terminologies for keys/secrets. In the key schedule we have the following:
------
sender_data_secret | "sender data"
encryption_secret | "encryption"
exporter_secret | "exporter"
authentication_secret | "authentication"
external_secret | "external"
confirmation_key | "confirm"
membership_key | "membership"
resumption_secret | "resumption"
-------

It would be best to provide a coherency to how we use these terms and check for consistency throughout, to avoid confusion for readers:

- A simple solution would be to use "secret" for all cases, i.e., changing membership_key to membership_secret. 

- Another alternative, which may take more refining but could be useful to readers is to separate out terms based on items that are for internal protocol use versus external protocol use. For example, encryption, confirmation, membership, etc., would use "key" and exporter, authentication, etc., could use "secret", or vice versa. 

--Break--

Ref the mailinglist on confirmation vs authentication secrets, perhaps the naming of these two are a little misleading - authentication normally being within bounds of a protocol while confirmation is external to it. This confusion probably sparked some of that discussion to begin with. It _could_ be worth considering switching those terms for clarity.

**Comment by bifurcation** [comment]
I actually think we have a fairly coherent taxonomy here:

* "secret" is something that gets fed into HKDF to derive further things
* "key" is something that gets fed into another algorithm, e.g., HMAC

Looking through the list, the ones that deviate from this pattern are:

1. `resumption_secret`, which is exported to the application but expected to be kept private
2. `authentication_secret`, which is exported to the application but not expected to be kept private

Given that, I would propose we update the table in question to something like the following, using `resumption_psk` because that's how it's used, and `authentication_code` to follow the "security code" terminology used by applications:

| Label           | Secret                | Usage                                             |
|:----------------|:----------------------|:--------------------------------------------------|
| "sender data"   | `sender_data_secret`  | Deriving keys to encrypt sender data              |
| "encryption"    | `encryption_secret`   | Deriving message encryption keys                  |
| "exporter"      | `exporter_secret`     | Deriving exported secrets                         |
| "external"      | `external_secret`     | Deriving the external init key                    |
| "confirm"       | `confirmation_key`    | Computing the confirmation MAC for an epoch       |
| "membership"    | `membership_key`      | Computing the membership MAC for an MLSPlaintext  |
| "resumption"    | `resumption_psk`      | Proving membership in a prior epoch (via a PSK)   |
| "authentication"| `authentication_code` | Confirming that two clients are in the same epoch |
