### ISSUE TITLE
Commit secret is ambiguous when root is blank

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-protocol#690]
As I was pondering pathological cases related to #645, it occurred to me that we already have a slightly odd situation that can arise as a result of the suppression of redundant nodes.  When a Commit has an UpdatePath, the `commit_secret` is defined as follows:

> Define commit_secret as the value path_secret[n+1] derived from the path_secret[n] value assigned to the root node.

However, there are situations where the root node is not assigned a value, namely when the left half of the tree is blank.  For example, suppose A creates a group with B, C, D:

```
      Y
    __|__
   /     \
  X       _ = Z
 / \     / \
A   B   C   D
```

Suppose that then C removes A and B, leaving C and D as the only leaves in the tree.  After removing A and B, the tree on which C computes an UpdatePath is as follows:

```
      _ = Y
    __|__
   /     \
  _       _ = Z
 / \     / \
_   _   C   D  
```

C's direct path is (Z, Y), but it's filtered direct path is just (Z) because the copath subtree of Y is all blank.  So C will not generate a path_secret for Y, which means that the commit secret is not really defined.

It seems like there are two paths to fix this:

1. Keep the current definition of `commit_secret` and require that a path secret always be generated for the root node
    * Presumably the root node path secret would be generated directly from the path secret in the UpdatePath
    * This would be simple to implement by just forcing the root node to be in the filtered direct path
2. Keep the current path secret generation and specify that the `commit_secret` is derived from the last path secret in the UpdatePath 
    * In the above example, the last path secret from the path secret for Z

I lean slightly toward (2) because it makes the computation the same for two neighbors regardless of where they are in the tree. It seems like the two options primarily differ in whether there are one or two invocations of the key derivation.

**Comment by bifurcation** [comment]
Interim 2022-05-26:

* @mulmarta supports doing "end of UpdatePath plus one"
* @bifurcation to write up a PR

**Comment by mulmarta** [comment]
First, both fixes are secure. I also lean towards (2), because it matches better my mental model: a) if any node (including root) has a child with a blank subtree, then it's blank, b) we generate `commit_secret` from the last secret generated by the committer.

@bifurcation while you're at it, you could also address the empty-UpdatePath ambiguity: If a member is alone in the group and sends a commit that doesn't add anyone, his UpdatePath is empty and he doesn't know how to derive `commit_secret`. This can happen even without filtered paths, if the tree has exactly 1 node. There are 2 solutions:

1. Pick a random secret
2. Disallow such commits

Regarding 2, does anyone know any reason we may want such commits?
