### ISSUE TITLE
IANA considerations for signature labels?

### ISSUE THREAD

**Issue by TWal** [mlswg/mls-protocol#840]
The `Label` of `SignWithLabel` absolutely needs to be unique for every signature happening in the protocol, for security and avoid signature ambiguity.
That includes signatures happening in extensions.

Should this be referenced in a IANA considerations to ensure there is no conflict in the future? Or at least say something about this somewhere?

We have to think how to design things well here to be future-proof: the `SignContent` structure must be used for every signature done with the leaf signature keys, which includes what might happen in extensions but also in future versions of MLS.
If future versions of MLS could avoid doing [what TLS 1.3 did to dis-ambiguate signatures with TLS 1.2](https://www.rfc-editor.org/rfc/rfc8446.html#section-4.4.3), that would be great!

**Comment by bifurcation** [comment]
This seems to come down to whether we expect the signature keys used for MLS authentication to be used outside of MLS (otherwise there's no risk of confusion) and if so, whether this spec has any influence on that usage. If you're using your MLS key to sign Bitcoin transactions, we can't do much to help that.  

Note that there is not an issue for future version of MLS here.  The label is constructed as `"MLS 1.0 " + Label`, so a future version could just increment the `1.0` part of that.

Given all that, I might prefer a recommendation that signature keys not be reused across contexts, rather than trying to accommodate reuse.

If we do something here, we should do something analogous to the [TLS exporter labels](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#exporter-labels) registry, which are similarly intended for domain separation between different use cases.  We should probably consider making an exporter label registry anyway.

**Comment by TWal** [comment]
I agree, we shouldn't do anything about someone using the MLS signature key in another protocol.

About future MLS versions: I agree, but note that there is a length tag before that.
It means that we impose to all signature of future MLS versions to start with `opaque label<V>;` (including the quic integer)
Is it something acceptable or not, I don't now. I just think we should have in mind that the decisions we make now on `SignContent` will have an impact on the design of future MLS versions.

About extensions: in the extensions document, there is a signature computed with `SignWithLabel(…, "TargetedMessageTBS", …)`
If two extensions were to use the same label then this could lead to security problems, this is why I think the labels should be in some registry to ensure they are all unique.
One other thing we could do is to separate all extensions signatures from the core MLS signatures, for exemple using the label "MLS 1.0 extension [label from extension]"? Like that a bogus extension can't introduce a security flaw in core MLS that way?
